package com.example.seacard

object CoverNames {
    val coverNameMap = mapOf(
        "4lapy.webp" to "Четыре Лапы",
        "366.webp" to "36,6",
        "1001kurtka.webp" to "1001 Куртка",
        "acoola.webp" to "Acoola",
        "aeroflot.webp" to "Аэрофлот",
        "albione.webp" to "ALBIONE",
        "amway.webp" to "Amway",
        "apple.webp" to "Apple",
        "aromatmir.webp" to "Ароматный мир",
        "artkvartal.webp" to "Арт-Квартал",
        "ashan.webp" to "Ашан",
        "automag.webp" to "АВТОМАГ",
        "automir.webp" to "Автомир",
        "azbucavkusa.webp" to "Азбука Вкуса",
        "bananamama.webp" to "Banana Мама",
        "baon.webp" to "Baon",
        "begemot.webp" to "Бегемот",
        "belaydacha.webp" to "Белая Дача",
        "belyikrolic.webp" to "Белый кролик",
        "belyiveter.webp" to "Белый Ветер",
        "bethoven.webp" to "Бетховен",
        "biblioglobus.webp" to "Библио-Глобус",
        "biomed.webp" to "Биомед",
        "bison.webp" to "Бизон",
        "bolshevichka.webp" to "Большевичка",
        "bookbridge.webp" to "BookBridge",
        "bork.webp" to "Bork",
        "bristol.webp" to "Бристоль",
        "bublgum.webp" to "Бубль Гум",
        "calipso.webp" to "Calipso",
        "calyaev.webp" to "Каляев",
        "centrobuv.webp" to "ЦентрОбувь",
        "cocialapteca.webp" to "Социальная аптека",
        "chesnok.webp" to "Чеснок",
        "chitaygorod.webp" to "Читай Город",
        "chizhik.webp" to "Чижик",
        "cl.webp" to "CL",
        "cmclinica.webp" to "СМ-Клиника",
        "coffehause.webp" to "Кофе Хауз",
        "coffemania.webp" to "Кофемания",
        "colins.webp" to "Colins",
        "columbia.webp" to "Columbia",
        "coolclever.webp" to "КУУЛКЛЕВЕР",
        "crazypark.webp" to "Crazy Park",
        "crocus.webp" to "CROCUS",
        "decatlon.webp" to "ДЕКАТЛОН",
        "detskij-mir.webp" to "Детский Мир",
        "diana.webp" to "Диана",
        "dicayaorchid.webp" to "Дикая Орхидея",
        "diksi.webp" to "Дикси",
        "divage.webp" to "DIVAGE",
        "dochkisynochki.webp" to "Дочки-Сыночки",
        "ecco.webp" to "ecco",
        "econica.webp" to "Эконика",
        "eldorado.webp" to "Эльдорадо",
        "evalar.webp" to "Эвалар Аптека",
        "familia.webp" to "Familia",
        "fanagoria.webp" to "FANAGORIA",
        "fasol.webp" to "Фасоль",
        "finnflaier.webp" to "Finn Flare",
        "fixprice.webp" to "Fix Price",
        "forman.webp" to "FORMAN",
        "formulazdorovya.webp" to "Формула Здоровья",
        "francescomarconi.webp" to "Francesco Marconi",
        "gamezona.webp" to "Game Zona",
        "gant.webp" to "GANT",
        "gazpromneft.webp" to "Газпромнефть",
        "goodfood.webp" to "Good Food",
        "gipfel.webp" to "Gipfel",
        "gloriajeans.webp" to "Gloria Jeans",
        "globus.webp" to "Глобус",
        "gum.webp" to "ГУМ",
        "hoff.webp" to "Hoff",
        "htc.webp" to "HTC",
        "hm.webp" to "H&M",
        "hyundai.webp" to "HYANDAI",
        "ildebote.webp" to "Иль Де Ботэ",
        "incanto.webp" to "Incanto",
        "invitro.webp" to "INVITRO",
        "ikornyi.webp" to "Икорный",
        "kant.webp" to "Кант",
        "kari.webp" to "Kari",
        "keddo.webp" to "KEDDO",
        "koleso.webp" to "Колесо",
        "komus.webp" to "Комус",
        "kotofey.webp" to "Котофей",
        "krasnoebeloe.webp" to "Красное & Белое",
        "krasnyclub.webp" to "Красный Куб",
        "laim.webp" to "Лайм",
        "laplandia.webp" to "Лапландия",
        "lenta.webp" to "ЛЕНТА",
        "leonardo.webp" to "Леонардо",
        "leroymerlen.webp" to "Лемана Про",
        "letual.webp" to "Л'Этуаль",
        "levis.webp" to "Levi's",
        "levistrauss.webp" to "Levi Strauss & Co",
        "loccitane.webp" to "L'Occitane",
        "loverepablic.webp" to "Love Republic",
        "lucoil.webp" to "Лукойл",
        "magnit.webp" to "Магнит",
        "magnolia.webp" to "Магнолия",
        "malina.webp" to "Малина",
        "meastfisha.webp" to "Мясо Рыба",
        "mediamarkt.webp" to "Media Markt",
        "mega.webp" to "МЕГА",
        "metro.webp" to "METRO",
        "mexx.webp" to "MEXX",
        "milana.webp" to "MILANA",
        "milavitsa.webp" to "MilaVitsa",
        "miratorg.webp" to "Мираторг",
        "mircosmetici.webp" to "Мир Косметики",
        "moresyshi.webp" to "Море Суши",
        "moscowdomknigi.webp" to "Московсикй Дом Книги",
        "mvideo.webp" to "М.Видео",
        "neofarm.webp" to "Неофарм",
        "niarmedic.webp" to "НИАРМЕДИК",
        "ochkarik.webp" to "Очкарик",
        "oggi.webp" to "OGGI",
        "okey.webp" to "О'Кей",
        "opticsity.webp" to "Оптик Сити",
        "ormatek.webp" to "Ортамек",
        "obi.webp" to "OBI",
        "oshade.webp" to "Oshade",
        "ostrov.webp" to "Остров",
        "otrix.webp" to "ORTIX",
        "palmetta.webp" to "Palmetta",
        "pariscimmuna.webp" to "Парижская коммуна",
        "perekrestok.webp" to "Перекрёсток",
        "petrovich.webp" to "Петрович",
        "petshopru.webp" to "Petshopru",
        "planetazdoroviy.webp" to "Планета Здоровья",
        "podrushka.webp" to "Подружка",
        "podsolnuh.webp" to "Подсолнух",
        "polaris.webp" to "Polaris",
        "pyaterochka.webp" to "Пятёрочка",
        "radugaapteca.webp" to "Аптека Радуга",
        "redmond.webp" to "REDMOND",
        "rigla.webp" to "Ригла",
        "rosneft.webp" to "Роснефть",
        "s7.webp" to "S7",
        "salamander.webp" to "Salamander",
        "savage.webp" to "Savage",
        "sela.webp" to "SELA",
        "sezon.webp" to "Сезон",
        "shokoladnica.webp" to "Шоколадница",
        "sokolov.webp" to "SOKOLOV",
        "snezhnaykoroleva.webp" to "Снежная Королева",
        "spar.webp" to "SPAR",
        "sportmaster.webp" to "Спортмастер",
        "stockmann.webp" to "Stockmann",
        "stolplit.webp" to "Столплит",
        "sudar.webp" to "Сударь",
        "sunlight.webp" to "Sunlight",
        "surgutneftegaz.webp" to "Сургутнефтегаз",
        "sushywok.webp" to "Суши Вок",
        "tehnopark.webp" to "Технопарк",
        "tehnosila.webp" to "Техно Сила",
        "tentorium.webp" to "Tentorium",
        "togas.webp" to "Togas",
        "tsum.webp" to "ЦУМ",
        "tvoe.webp" to "ТВОЕ",
        "tvoydom.webp" to "Твой Дом",
        "uralairlines.webp" to "Уральские авиалинии",
        "utair.webp" to "UTair",
        "utkonos.webp" to "Утконос",
        "vernyi.webp" to "Верный",
        "vita.webp" to "ВИТА",
        "vkusvill.webp" to "ВкусВилл",
        "viktoria.webp" to "Виктория",
        "yakitoria.webp" to "Якитория",
        "ypalucha.webp" to "У Палыча",
        "yvesrocher.webp" to "Yves Rocher",
        "yuzhnyi.webp" to "Южный+",
        "zarina.webp" to "Zarina",
        "zenden.webp" to "ZENDEN",
        "zolotoeyabloco.webp" to "Золотое Яблоко"
    )
} 