package ru.merrcurys.seacard.core.utils

object CoverNames {
    val coverNameMap = mapOf(
        "4lapy.webp" to "Четыре Лапы",
        "366.webp" to "36,6",
        "5zvezd.webp" to "Пять звезд",
        "585gold.webp" to "585 Золотой",
        "acoola.webp" to "Acoola",
        "adamas.webp" to "Adamas",
        "aeroflot.webp" to "Аэрофлот",
        "agrocompleks.webp" to "Агрокомплекс",
        "agusha.webp" to "Агуша",
        "alba.webp" to "Alba",
        "albione.webp" to "ALBIONE",
        "alenka.webp" to "Алёнка",
        "almazholding.webp" to "Алмаз-холдинг",
        "aptekapiter.webp" to "Петербургские аптеки",
        "aptechnykoshelek.webp" to "Будь Здоров!",
        "aptekiplus.webp" to "Аптеки Плюс",
        "aptekafamily.webp" to "Аптечная семья",
        "arbormundy.webp" to "Арбор Мунди",
        "aromatmir.webp" to "Ароматный мир",
        "artkvartal.webp" to "Арт-Квартал",
        "ashan.webp" to "Ашан",
        "avoska.webp" to "Авоська",
        "avgustina.webp" to "Августина",
        "afina.webp" to "Афина",
        "avtoall.webp" to "Avto All",
        "automag.webp" to "АВТОМАГ",
        "automir.webp" to "Автомир",
        "azbucavkusa.webp" to "Азбука Вкуса",
        "b1.webp" to "В1",
        "baon.webp" to "Baon",
        "barbos.webp" to "Барбос",
        "belaydacha.webp" to "Белая Дача",
        "belleyou.webp" to "Belle You",
        "belwest.webp" to "Belwest",
        "belyikrolic.webp" to "Белый кролик",
        "benartti.webp" to "Benartti",
        "bethoven.webp" to "Бетховен",
        "biblioglobus.webp" to "Библио-Глобус",
        "birzhavkusov.webp" to "Мясницкий ряд",
        "biomed.webp" to "Биомед",
        "bison.webp" to "Бизон",
        "bolshevichka.webp" to "Большевичка",
        "bookbridge.webp" to "BookBridge",
        "bork.webp" to "Bork",
        "bristol.webp" to "Бристоль",
        "bronnickiyuvelir.webp" to "Бронницкий Ювелир",
        "bublgum.webp" to "Бубль Гум",
        "bukvoed.webp" to "Буквоед",
        "burgerking.webp" to "Burger King",
        "calipso.webp" to "Calipso",
        "calzedonia.webp" to "Calzedonia",
        "calyaev.webp" to "Каляев",
        "cocialapteca.webp" to "Социальная аптека",
        "corsocomo.webp" to "CORSO COMO",
        "chesnok.webp" to "Чеснок",
        "chitaygorod.webp" to "Читай Город",
        "chizhik.webp" to "Чижик",
        "cl.webp" to "CL",
        "cmclinica.webp" to "СМ-Клиника",
        "cofix.webp" to "Cofix",
        "coffehause.webp" to "Кофе Хауз",
        "coffelike.webp" to "Coffe Like",
        "coffemania.webp" to "Кофемания",
        "colins.webp" to "Colins",
        "columbia.webp" to "Columbia",
        "coolclever.webp" to "КУУЛКЛЕВЕР",
        "crazypark.webp" to "Crazy Park",
        "crocus.webp" to "CROCUS",
        "desport.webp" to "Desport",
        "detskij-mir.webp" to "Детский Мир",
        "diana.webp" to "Диана",
        "dicayaorchid.webp" to "Дикая Орхидея",
        "diksi.webp" to "Дикси",
        "drinkit.webp" to "Дринкит",
        "drinx.webp" to "Drinx",
        "divage.webp" to "DIVAGE",
        "dns.webp" to "DNS",
        "domovoy.webp" to "Домовой",
        "ecco.webp" to "ecco",
        "econica.webp" to "Эконика",
        "economstroy.webp" to "Экономстрой",
        "ermolaev.webp" to "Ермолаевъ",
        "elize.webp" to "ЭЛИЗЭ",
        "evalar.webp" to "Эвалар Аптека",
        "familia.webp" to "Familia",
        "fanagoria.webp" to "FANAGORIA",
        "farmlend.webp" to "Фармленд",
        "fasol.webp" to "Фасоль",
        "finnflaier.webp" to "Finn Flare",
        "fixprice.webp" to "Fix Price",
        "forman.webp" to "FORMAN",
        "forward.webp" to "Forward",
        "formulazdorovya.webp" to "Формула Здоровья",
        "francescomarconi.webp" to "Francesco Marconi",
        "funday.webp" to "FunDay",
        "gamezona.webp" to "Game Zona",
        "galamart.webp" to "Галамарт",
        "gazpromneft.webp" to "Газпромнефть",
        "goodfood.webp" to "Good Food",
        "gorzdrav.webp" to "Горздрав",
        "gipfel.webp" to "Gipfel",
        "gloriajeans.webp" to "Gloria Jeans",
        "globus.webp" to "Глобус",
        "gum.webp" to "ГУМ",
        "hoff.webp" to "Hoff",
        "hohyeshe.webp" to "Хочу ещё!",
        "hm.webp" to "H&M",
        "hyundai.webp" to "Hyundai",
        "ildebote.webp" to "Иль Де Ботэ",
        "incanto.webp" to "Incanto",
        "intimissimi.webp" to "Intimissimi",
        "invitro.webp" to "INVITRO",
        "imperiasumok.webp" to "Империя сумок",
        "ikornyi.webp" to "Икорный",
        "jeffreyscoffeshop.webp" to "Jeffrey's Coffeshop",
        "kant.webp" to "Кант",
        "kantata.webp" to "Кантата",
        "kari.webp" to "Kari",
        "keddo.webp" to "KEDDO",
        "koleso.webp" to "Колесо",
        "komus.webp" to "Комус",
        "kotofey.webp" to "Котофей",
        "krasnoebeloe.webp" to "Красное & Белое",
        "laplandia.webp" to "Лапландия",
        "legkiyshag.webp" to "Легкий шаг",
        "lenta.webp" to "ЛЕНТА",
        "leonardo.webp" to "Леонардо",
        "lemanapro.webp" to "Лемана Про",
        "letual.webp" to "Л'Этуаль",
        "levistrauss.webp" to "Levi Strauss & Co",
        "lekopttorg.webp" to "ЛекОптТорг",
        "loverepablic.webp" to "Love Republic",
        "lucoil.webp" to "Лукойл",
        "magnit.webp" to "Магнит",
        "mariara.webp" to "Мария Ра",
        "magnolia.webp" to "Магнолия",
        "maksidom.webp" to "Максидом",
        "meastfisha.webp" to "Мясо Рыба",
        "medi.webp" to "medi",
        "metro.webp" to "METRO",
        "milana.webp" to "MILANA",
        "mila.webp" to "Мила",
        "milavitsa.webp" to "MilaVitsa",
        "mokruinos.webp" to "Мокрый нос",
        "miratorg.webp" to "Мираторг",
        "moresyshi.webp" to "Море Суши",
        "moscowdomknigi.webp" to "Московсикй Дом Книги",
        "monetka.webp" to "Монетка",
        "mvideo.webp" to "М.Видео",
        "neofarm.webp" to "Неофарм",
        "niarmedic.webp" to "НИАРМЕДИК",
        "ochkarik.webp" to "Очкарик",
        "oodji.webp" to "oodji",
        "okey.webp" to "О'Кей",
        "opticsity.webp" to "Оптик Сити",
        "okraina.webp" to "Окраина",
        "oneanddouble.webp" to "One and Double",
        "onepricecoffee.webp" to "One Price Coffee",
        "ormatek.webp" to "Ортамек",
        "domlenta.webp" to "Дом лента",
        "oshade.webp" to "Oshade",
        "ostin.webp" to "O'stin",
        "ozerki.webp" to "Аптеки Озёрки",
        "oldi.webp" to "OLDI",
        "otrix.webp" to "ORTIX",
        "orteca.webp" to "ОРТЕКА",
        "palmetta.webp" to "Palmetta",
        "pariscimmuna.webp" to "Парижская коммуна",
        "perekrestok.webp" to "Перекрёсток",
        "petrovich.webp" to "Петрович",
        "petshopru.webp" to "Petshopru",
        "planetazdoroviy.webp" to "Планета Здоровья",
        "podrushka.webp" to "Подружка",
        "podsolnuh.webp" to "Подсолнух",
        "polaris.webp" to "Polaris",
        "pyaterochka.webp" to "Пятёрочка",
        "radugaapteca.webp" to "Аптека Радуга",
        "redmond.webp" to "REDMOND",
        "rigla.webp" to "Ригла",
        "rodnikzdorovia.webp" to "Родник Здоровья",
        "rivgosh.webp" to "РИВ ГОШ",
        "rosneft.webp" to "Роснефть",
        "rublevskiy.webp" to "Рублёвский",
        "s7.webp" to "S7",
        "salamander.webp" to "Salamander",
        "savage.webp" to "Savage",
        "sela.webp" to "SELA",
        "sezon.webp" to "Сезон",
        "shokoladnica.webp" to "Шоколадница",
        "sitylink.webp" to "Ситилинк",
        "sokolov.webp" to "SOKOLOV",
        "snezhnaykoroleva.webp" to "Снежная Королева",
        "spar.webp" to "SPAR",
        "sportmaster.webp" to "Спортмастер",
        "starscoffee.webp" to "Stars Coffee",
        "stockmann.webp" to "Stockmann",
        "stolplit.webp" to "Столплит",
        "stolichki.webp" to "Аптеки Столички",
        "svetofor.webp" to "Светофор",
        "sudar.webp" to "Сударь",
        "surfcoffee.webp" to "Surf Coffee",
        "sunlight.webp" to "Sunlight",
        "surgutneftegaz.webp" to "Сургутнефтегаз",
        "sushywok.webp" to "Суши Вок",
        "tatneft.webp" to "ТатНефть",
        "tehnopark.webp" to "Технопарк",
        "tentorium.webp" to "Tentorium",
        "togas.webp" to "Togas",
        "teboil.webp" to "Teboil",
        "tsum.webp" to "ЦУМ",
        "tvoe.webp" to "ТВОЕ",
        "tvoydom.webp" to "Твой Дом",
        "uralairlines.webp" to "Уральские авиалинии",
        "utair.webp" to "UTair",
        "vernyi.webp" to "Верный",
        "vita.webp" to "ВИТА",
        "vinlab.webp" to "Винлаб",
        "vkusvill.webp" to "ВкусВилл",
        "wienerwald.webp" to "Wiener Wald",
        "x5.webp" to "X5 Клуб",
        "yakitoria.webp" to "Якитория",
        "yarche.webp" to "Ярче!",
        "ypalucha.webp" to "У Палыча",
        "ylubkaradugi.webp" to "Улыбка Радуги",
        "yvesrocher.webp" to "Yves Rocher",
        "yuzhnyi.webp" to "Южный+",
        "zarina.webp" to "Zarina",
        "zenden.webp" to "ZENDEN",
        "zdravsity.webp" to "Здравсити",
        "zolotoeyabloco.webp" to "Золотое Яблоко"
    )
}
